---
###############################################################################
# Zsh installation

- name: zsh | Installs zsh | apt
  become: yes
  apt:
    name: zsh
    state: present

- name: zsh | Sets zsh as default shell for root | command
  become: yes
  command: chsh -s /bin/zsh
  register: zsh_for_root
  failed_when: zsh_for_root.rc >= 1
  changed_when: zsh_for_root.rc == 0

- name: zsh | Sets zsh as default shell for {{ dotfiles_user }} | command
  become: yes
  command: chsh -s /bin/zsh {{ dotfiles_user }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: zsh | Check if oh-my-zsh already exists in /opt | stat 
  stat: 
    path: /opt/oh-my-zsh/
  register: opt_oh_my_zsh

- name: zsh | Installs oh-my-zsh | raw
  raw: 'ZSH=/opt/oh-my-zsh sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  become: yes
  when: not opt_oh_my_zsh.stat.exists

- name: zsh | Create zsh config directories | file
  file:
    path: "{{ dotfiles_config_root }}/zsh/.zsh"
    state: directory

- name: zsh | Copies .zshrc | template
  template:
    src: "zshrc.j2"
    dest: "{{ dotfiles_config_root }}/zsh/.zshrc"
    force: yes

- name: zsh | Installs hab | git
  git:
    repo: "https://github.com/alexdesousa/hab.git"
    dest: "/opt/oh-my-zsh/custom/plugins/hab"
    clone: yes
    update: yes
    force: yes
  become: yes
