---
###############################################################################
# Shell utilities installation

- name: SHELL | Installs command line tools | apt
  become: yes
  loop: "{{ shell_packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name: SHELL | Copies shell.zsh to zsh config directory | copy
  copy:
    src: "shell.zsh"
    dest: "{{ dotfiles_config_root }}/zsh/.zsh/shell.zsh"
    force: yes