---
###############################################################################
# ASDF installation

- name: asdf | Installs asdf | git
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ asdf_dir }}"
    version: "v{{ asdf_version }}"
    clone: yes
    update: yes
    force: yes
  become: yes

- name: asdf | Create asdf config directory | file
  file:
    path: "{{ dotfiles_config_root }}/asdf/.asdf/"
    state: directory

- name: asdf | Copies asdf.zsh to zsh config | template
  template:
    src: "asdf.zsh.j2"
    dest: "{{ dotfiles_config_root }}/zsh/.zsh/asdf.zsh"

- name: asdf | Copies .asdfrc to config | template
  template:
    src: "asdfrc.j2"
    dest: "{{ dotfiles_config_root }}/asdf/.asdfrc"

- name: asdf | Common build utilities | apt
  become: yes
  loop: "{{ build_packages }}"
  apt:
    name: "{{ item }}"
    state: present