---
###############################################################################
# ASDF installation

- name: asdf | Installs asdf | git
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "/opt/asdf"
    version: "v{{ asdf_version }}"
    clone: yes
    update: yes
    force: yes
  become: yes

- name: asdf | Create asdf config directory | file
  file:
    path: "{{ dotfiles_config_root }}/asdf/.asdf/"
    state: directory

- name: asdf | Copies asdf.zsh | copy
  copy:
    src: "asdf.zsh"
    dest: "{{ dotfiles_config_root }}/asdf/.asdf/asdf.zsh"
    force: yes

- name: asdf | Link asdf.zsh to zsh config | file
  file:
    src: "{{ dotfiles_config_root }}/asdf/.asdf/asdf.zsh"
    dest: "{{ dotfiles_config_root }}/zsh/.zsh/asdf.zsh"
    state: link
    force: yes

- name: asdf | Common build utilities | apt
  become: yes
  loop: "{{ build_packages }}"
  apt:
    name: "{{ item }}"
    state: present