---
###############################################################################
# Ruby installation

- name: Ruby | Installs Ruby plugin | command
  command: "{{ asdf_bin }} plugin-add ruby"
  register: ruby_add
  failed_when: ruby_add.rc == 1

- name: Ruby | Updates Ruby plugin | command
  command: "{{ asdf_bin }} plugin-update ruby"

- name: Ruby | Installs Ruby versions | shell
  shell: "source {{ asdf_src }} && asdf install ruby {{ item }}"
  args:
    executable: /bin/zsh
  loop: "{{ ruby_versions }}"

- name: Ruby | Sets default Ruby version | command
  shell: "source {{ asdf_src }} && asdf global ruby {{ ruby_versions[0] }}"
  args:
    executable: /bin/zsh

- name: Ruby | Reshims Ruby | shell
  shell: "source {{ asdf_src }} && asdf reshim ruby"
  args:
    executable: /bin/zsh