---
###############################################################################
# VsCode installation

- name: Code | Gets code dependencies | apt
  become: yes
  loop: "{{ code_dependencies }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Code | Gets APT key for code | apt_key
  become: yes
  apt_key:
    url: "{{ code_gpg_key }}"
    state: present

- name: Code | Updates repositories | apt_repository
  become: yes
  apt_repository:
    repo: "{{ code_repository }}"
    state: present
    filename: code

- name: Code | Installs code | apt
  become: yes
  loop: "{{ code_packages }}"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes

- name: Code | Install extensions | shell
  loop: "{{ code_extensions }}"
  shell: "code --install-extension {{ item }}"

- name: Code | Create vscode config directory | file
  file:
    path: "{{ dotfiles_config_root }}/code/{{ code_settings_path }}"
    state: directory

- name: Code | Copy settings to config | copy
  copy:
    src: "{{ dotfiles_ansible_root }}/roles/code/files/settings.json"
    dest: "{{ dotfiles_config_root }}/code/{{ code_settings_path }}/settings.json"