---
###############################################################################
# Spotify installation

- name: Spotify | Gets APT key for spotify | apt_key
  become: yes
  apt_key:
    url: "{{ spotify_gpg_key }}"
    state: present

- name: Spotify | Updates repositories | apt_repository
  become: yes
  apt_repository:
    repo: "{{ spotify_repository }}"
    state: present
    filename: spotify

- name: Spotify | Installs spotify | apt
  become: yes
  loop: "{{ spotify_packages }}"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes