---
###############################################################################
# Erlang installation

- name: Erlang | Installs dependencies | apt
  become: yes
  loop: "{{ erlang_dependencies }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Erlang | Copies erlang.zsh to zsh directory | copy
  copy:
    src: "erlang.zsh"
    dest: "{{ dotfiles_config_root }}/zsh/.zsh/erlang.zsh"
    force: yes

- name: Erlang | Installs Erlang plugin | shell
  command: "{{ asdf_bin }} plugin-add erlang"
  register: erlang_add
  failed_when: erlang_add.rc == 1

- name: Erlang | Updates Erlang plugin | shell
  command: "{{ asdf_bin }} plugin-update erlang"

- name: Erlang | Installs Erlang versions | shell
  shell: "source {{ asdf_src }} && asdf install erlang {{ item }}"
  args:
    executable: /bin/zsh
  loop: "{{ erlang_versions }}"

- name: Erlang | Sets default Erlang version | command
  shell: "source {{ asdf_src }} && asdf global erlang {{ erlang_versions[0] }}"
  args:
    executable: /bin/zsh

- name: Erlang | Reshims Erlang | shell
  shell: "source {{ asdf_src }} && asdf reshim erlang"
  args:
    executable: /bin/zsh