---
###############################################################################
# NodeJS installation

- name: NodeJS | Installs dependencies | apt
  become: yes
  loop: "{{ nodejs_dependencies }}"
  apt:
    name: "{{ item }}"
    state: present

- name: NodeJS | Installs NodeJS plugin | command
  command: "{{ asdf_bin }} plugin-add nodejs"
  register: nodejs_add
  failed_when: nodejs_add.rc == 1

- name: NodeJS | Creates GNUPGHOME folder | command
  file:
    path: "{{ nodejs_gnupghome }}"
    state: directory
    mode: '0700'

- name: NodeJS | Imports release team keyring | shell
  shell: "{{ asdf_data_dir }}/plugins/nodejs/bin/import-release-team-keyring"
  environment:
    GNUPGHOME: "{{ nodejs_gnupghome }}"

- name: NodeJS | Installs NodeJS versions | shell
  shell: "source {{ asdf_src }} && asdf install nodejs {{ item }}"
  args:
    executable: /bin/zsh
  loop: "{{ nodejs_versions }}"
  environment:
    GNUPGHOME: "{{ nodejs_gnupghome }}"
    NODEJS_CHECK_SIGNATURES: "yes"

- name: NodeJS | Sets default NodeJS version | command
  shell: "source {{ asdf_src }} && asdf global nodejs {{ nodejs_versions[0] }}"
  args:
    executable: /bin/zsh
  environment:
    GNUPGHOME: "{{ nodejs_gnupghome }}"
    NODEJS_CHECK_SIGNATURES: "yes"

- name: NodeJS | Reshims NodeJS | shell
  shell: "source {{ asdf_src }} && asdf reshim nodejs"
  args:
    executable: /bin/zsh

- name: NodeJS | Update NPM | shell
  shell: "source {{ asdf_src }} && npm install npm@latest -g"
  args:
    executable: /bin/zsh