---
###############################################################################
# Git installation

- name: Git | Installs git | apt
  become: yes
  become_user: root
  apt:
    name: git
    state: present

- name: Git | Copy global gitignore file | copy
  copy:
    src: "{{ dotfiles_ansible_root }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_config_root }}/.gitignore_global"
    force: yes

- name: Git | Copies git config | template
  template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_config_root }}/.gitconfig"