---
###############################################################################
# Git installation

- name: Git | Installs git | apt
  become: yes
  become_user: root
  apt:
    name: git
    state: present

- name: git | Create git config directory | file
  file:
    path: "{{ dotfiles_config_root }}/git/"
    state: directory

- name: Git | Copy global gitignore file | copy
  copy:
    src: "{{ dotfiles_ansible_root }}/roles/git/files/gitignore_global"
    dest: "{{ dotfiles_config_root }}/git/.gitignore_global"
    force: yes

- name: Git | Copies git config | template
  template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_config_root }}/git/.gitconfig"