---
###############################################################################
# Shell mail

- name: mail | Check mail_hostname is defined | assert
  assert:
    that:
      - "mail_hostname is defined"
      - "mail_hostname | length > 0"
      - "mail_hostname != None"
    fail_msg: "mail_hostname needs to be set for the role to work"
    success_msg: "Required variable mail_hostname is defined"

- name: mail | Check mail_relay_host is defined | assert
  assert:
    that:
      - "mail_relay_host is defined"
      - "mail_relay_host | length > 0"
      - "mail_relay_host != None"
    fail_msg: "mail_relay_host needs to be set for the role to work"
    success_msg: "Required variable mail_relay_host is defined"

- name: mail | Check mail_smtp_app_key is defined | assert
  assert:
    that:
      - "mail_smtp_app_key is defined"
      - "mail_smtp_app_key | length > 0"
      - "mail_smtp_app_key != None"
    fail_msg: "mail_smtp_app_key needs to be set for the role to work"
    success_msg: "Required variable mail_smtp_app_key is defined"

- name: mail | Configure postfix mailname | debconf
  become: yes
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ mail_hostname }}"
    vtype: string

- name: mail | Configure postfix mailer type | debconf
  become: yes
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Satellite system"
    vtype: select

- name: mail | Configure postfix relay host | debconf
  become: yes
  debconf:
    name: postfix
    question: postfix/relayhost
    value: "{{ mail_relay_host }}"
    vtype: string

- name: mail | Install packages | apt
  become: yes
  loop: "{{ mail_packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name: mail | Copy postfix configuration | template
  become: yes
  template:
    src: "main.cf.j2"
    dest: "/etc/postfix/main.cf"
    backup: yes

- name: mail | Copy smtp relay configuration | template
  become: yes
  template:
    src: "relay_passwd.j2"
    dest: "/etc/postfix/sasl/relay_passwd"
    backup: yes

- name: mail | Generate postfix credential files | shell
  become: yes
  shell: "postmap /etc/postfix/sasl/relay_passwd"
  
- name: mail | Secure postfix credential files | file
  become: yes
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0400'
  with_items:
    - /etc/postfix/sasl/relay_passwd
    - /etc/postfix/sasl/relay_passwd.db

- name: mail | Restart postfix service | service
  become: yes
  service:
    name: postfix
    state: restarted

- name: mail | Create mutt config directory | file
  file:
    path: "{{ dotfiles_config_root }}/mutt"
    state: directory

- name: mail | Copy mutt configuration | template
  template:
    src: "muttrc.j2"
    dest: "{{ dotfiles_config_root }}/mutt/.muttrc"
    force: yes