---
###############################################################################
# Base system

- name: Base | Update and upgrade packages | apt
  become: yes
  become_user: root
  apt:
          upgrade: 'yes'
          update_cache: yes

- name: Base | Installs packages | apt
  become: yes
  become_user: root
  loop: "{{ base_packages }}"
  apt:
          name: "{{ item }}"
          state: present

- name: Base | Cleans packages | apt
  become: yes
  become_user: root
  apt:
          autoremove: yes
